### ISSUE TITLE
Unable to instantiate class at runtime

### ISSUE THREAD

**Issue by JordanKadish** [scrapy-plugins/scrapy-jsonschema#17]
The following code produces an error, but I feel this should absolutely be possible to do:
```
from scrapy_jsonschema.item import JsonSchemaItem

class LinktItem(JsonSchemaItem):
    def __init__(self, jsonschema):
        self.jsonschema = jsonschema


jsonschema = {
    'properties': {
        'url': {
            'description': 'full URL to the item',
            'type': 'string',
            'format': 'url'
        },
        "sourceName": {
            "description": "name of source website",
            "type": "string"
        }
    },
    'definitions': {
        'non-empty-string': {
            'type': 'string',
                    'minLength': 1
        }
    }
}

test = LinkItem(jsonschema)
print(test)
```

Error produced:
```
Traceback (most recent call last):
  File "/workspace/gencrawl/spiders/test.py", line 4, in <module>
    class LinktItem(JsonSchemaItem):
  File "/usr/local/lib/python3.6/site-packages/scrapy_jsonschema/item.py", line 77, in __new__
    '{} must contain "jsonschema" attribute'.format(cls.__name__)
ValueError: LinktItem must contain "jsonschema" attribute
```
As we see in init, LinkItem _does_ contain jsonschema

**Comment by BurnzZ** [comment]
Hi @JordanKadish , this errors stems from [these lines of code](https://github.com/scrapy-plugins/scrapy-jsonschema/blob/master/scrapy_jsonschema/item.py#L67-L78) inside the `__new__()` method.

In the code snippet you've attached, you've assigned the `jsonschema` inside the `__init__()` method, which makes it an **instance variable**. However, `scrapy-jsonschema` needs the `jsonschema` to be declared as a **class variable** which is shared across all instances of the class. This means it needs to be declared outside of the `__init__()` method.

This is an important feature because of the following properties:

```
class Foo:
    def __init__(self, value):
        self.value = value

class Bar:
    value = 0


# has 'value' as instance variable
foo_1 = Foo(0)  
foo_2 = Foo(0)  

# has 'value' as class variable
bar_1 = Bar() 
bar_2 = Bar()

foo_1.value = 1
foo_2.value  # this is still 0

bar_1.value = 1
bar_2.value  # this is still 0

Bar.value = 99

bar_1.value  # this is still 1
bar_2.value  # this has changed to 99
```

Writing your class as the following would be the correct way of doing it:
```
class LinkItem(JsonSchemaItem):
    jsonschema = jsonschema
```

Closing this for now but feel free to reopen if you need more clarification. Cheers!
